CREATE TABLE IF NOT EXISTS PLAYER (
  PLAYER_ID VARCHAR(20) PRIMARY KEY,
  PLAYER_NAME TEXT,
  PLAYER_NUMBER TEXT,
  PLAYER_POSITION TEXT
);
INSERT INTO PLAYER (PLAYER_ID, PLAYER_NAME, PLAYER_NUMBER, PLAYER_POSITION) VALUES
  ('1', 'GIANLUIGI DONNARUMMA', '25', 'GOALKEEPER'),
  ('2', 'RUBEN DIAS', '3', 'CENTRER BACK'),
  ('3', 'JOSKO GVARDIOL', '24', 'LEFT BACK'),
  ('4', 'RAYAN AIT-NOURI', '21', 'RIGHT BACK'),
  ('5', 'ABDUKODIR KHUSANOV', '45', 'CENTER BACK'),
  ('6', 'RODRI', '16', 'CENTER MIDFIELDER'),
  ('7', 'BERNARDO SILVA', '20', 'CENTER MIDFIELDER'),
  ('8', 'RAYAN CHERKI', '10', 'CENTER MIDFIELDER'),
  ('9', 'JEREMY DOKU', '11', 'LEFT WINGER'),
  ('10', 'ANTONINE SEMENYO', '42', 'RIGHT WINGER'),
  ('11', 'ERLING HAALAND', '9', 'STRIKER');

SELECT * FROM PLAYER;
SELECT * FROM PLAYER
WHERE PLAYER_POSITION = 'GOALKEEPER';
SELECT * FROM PLAYER
WHERE PLAYER_POSITION = 'LEFT BACK' AND PLAYER_NAME = 'RAYAN AIT-NOURI';
SELECT * FROM PLAYER
WHERE PLAYER_NUMBER = '3' OR PLAYER_NUMBER = '45';
SELECT * FROM PLAYER
WHERE PLAYER_POSITION = 'CENTER MIDFIELDER'
SELECT * FROM PLAYER
WHERE PLAYER_NUMBER = '42' AND (PLAYER_NAME = 'ERLING HAALAND' OR PLAYER_POSITION = 'LEFT WINGER');